### PR TITLE
attempt to delimit more complex commands

### PR DESCRIPTION
**Pull request by rdallman**
here we do 2 things:
* single quote any args that were multiple args, i.e. ["sh", "-c", "some command"] -> sh -c 'some command'
* escape any single quotes inside of multiple args args.
since docker basically doesn't allow things like:
    `$ docker run some/image sh -c "cmd $(some command)"`
to exec inside of the docker container anyway (i.e. $(some command) will be run on host),
we're not really sacrificing any functionality. I could be wrong here.

i tested with a few commands after finally coming to the above mentioned conclusion. if somebody smarter than me can confirm that it's right i will feel a little bit better about the whole thing. probably need to release into the wild or/and try to do some weird shit.

@treeder thoughts?

### CODE REVIEW

**Comment by rdallman** [comment]
and no updates to swapi/runner necessary for this to work

**Comment by thousandsofthem** [comment]
That's the *client* side. Anyone can bypass it (using curl e.g.) is swapi/runner protected here?

**Comment by rdallman** [comment]
the main issue is that we write the command out into a file as opposed to passing a list of arguments in order to avoid that situation. i.e. if you want to run a command: `echo $(whoami)`, we write that command out to a file and do `sh $file` _inside_ docker container. so docker command ends up being `docker run some/image sh $file`.

anyway, already running into issues here if command was originally `echo "something really weird"` and we rewrite it to `echo 'something really weird'`. anybody else have ideas? losing it

**Comment by edsrzf** [comment]
What if you used xargs to run the command? Something like:

    xargs sh < file

Then no shell characters will be interpreted. The only issue might be if one of the arguments contains a newline, but if that's a concern then you could use a different delimiter, like maybe the null character.

**Comment by vasilev** [comment]
@rdallman , it seems you are trying to implement http://php.net/escapeshellarg functionality.
https://github.com/php/php-src/blob/master/ext/standard/exec.c#L341 archives it by gluing together single-quoted parts and quoted apostrophe between them:
`"echo There's a snake"` => `'echo There'\''s a snake'`
`"echo There\'s a snake"` => `'echo There\'\''s a snake'` .

Tests for `escapeshellarg`: https://github.com/php/php-src/blob/master/ext/standard/tests/general_functions/escapeshellarg_basic.phpt .

**Comment by thousandsofthem** [comment]
Ruby:
http://ruby-doc.org/stdlib-2.0.0/libdoc/shellwords/rdoc/Shellwords.html#method-c-shellescape

**Comment by rdallman** [comment]
thank you all for suggestions. php version worked. yay. updated commit. please try to break it :)

**Comment by rdallman** [comment]
@treeder did you give this a whirl on your whizz bang commands ?

**Comment by dukelion** [comment]
We could encode command in base64 and use ```sh -c "echo $MYCOMMAND | base64 -d | sh"``` to avoid escaping issues.

**Comment by rdallman** [comment]
interesting. i think we're going to move to passing the command around as a list of strings once the go runner is ready / if we move to using docker remote api before hand.

**Comment by Nyarum** [comment]
@rdallman ok to close?

**Pull request closed without merging**
