### PR TITLE
move to docker command thingy w/ zip upload --  DON'T MERGE

### PR DESCRIPTION
**Pull request by rdallman**
doesn't really work, not supported by iron_worker, but this may work
once it's fixed up... will need to test.

scrapped all the old .worker stuff. can add it back if we really want it (it wasn't very robust to begin with wrt upload)

TODO support local "run" with this style

### CODE REVIEW

**Comment by rdallman** [comment]
@treeder https://github.com/iron-io/swapi/pull/278#issuecomment-69058819 resolved

**Comment by treeder** [comment]
Ok, couple things:

- specify full zip file, not just the name of the zip, eg: upload hello.zip (that doesn't work, it has to be upload hello right now)
- make the worker name, the name of the zip file minus the .zip.

Or is that kind of confusing since the queue part would be without the zip?

**Comment by rdallman** [comment]
should be resolved. i don't think the "queue" thing is too confusing, just need to doc it

**Comment by treeder** [comment]
Much better, thanks!

**Pull request merged**
