### PR TITLE
Windows MSI installer

### PR DESCRIPTION
**Pull request by pyeremenko**
**UPD:** As PowerShell and Windows CMD console are very strange things, we decided to implement MSI installer. I tried to describe everything in README.md

Don't read text below 

----

*Original text*

*Windows PowerShell is built for 32 bit arch. So PowerShell on x86 virtual machine tells:*

```
C:\Users\admin\Documents\GitHub> uname
MINGW32_NT-6.1
C:\Users\admin\Documents\GitHub> uname -m
i686
```

*...as expected. But on real x64 installation of Windows 8.1 it also tells*

```
freeman@FREEMAN-ASUS> uname
MINGW32_NT-8.1
freeman@FREEMAN-ASUS> uname -m
i686
```

*There are several possible ways of Windows architecture detection:*

* *echo $ENV:PROCESSOR_ARCHITECTURE*
* *[IntPtr]::Size*

*First seems to be preferable because on Linux it doesn't cause errors and just tells* `:PROCESSOR_ARCHITECTURE`

### CODE REVIEW

**Comment by pyeremenko** [comment]
**UPD:** 

Both `echo $ENV:PROCESSOR_ARCHITECTURE` and `[IntPtr]::Size` returns 32 on x64 machines in some cases.

`(Get-WmiObject Win32_OperatingSystem).OSArchitecture` seems to work better

**Comment by pyeremenko** [comment]
@treeder, @rdallman please, give your feedback

@freeman1988, please also take a look

**Comment by treeder** [comment]
I can't really test this, sorry.

**Comment by rdallman** [comment]
me neither, @freeman1988 maybe? going to merge, i think it's good to go, I talked to peter over the last few days he has been working on it / testing. this just has instructions for how to build it for future us and we can drop the exe file into the release page

**Comment by pyeremenko** [comment]
@treeder, @rdallman I just asked you to look at READMEs - are they clear for you?

**Comment by rdallman** [comment]
Yep, READMEs are great. Just can't test the MSI myself but I'm sure you did

**Pull request merged**
