### PR TITLE
don't overwrite upload args on each upload -- it's what the people want

### PR DESCRIPTION
**Pull request by rdallman**
re: https://app.intercom.io/a/apps/u9ytpaii/inbox/conversation/992216314

as a side effect, now you can no longer 'reset' values, since we're using the zero value to determine whether it was set, but if this is what the people want then okay... we could use pointers.

tested, it works.

### CODE REVIEW

**Comment by rdallman** [comment]
@treeder

**Comment by thousandsofthem** [comment]
@rdallman shouldn't it be distinction between "i didn't pass anything, keep as is" and "passed empty value, want to erase" ?

**Comment by treeder** [comment]
Should use pointers, but this is probably ok for now.

**Comment by treeder** [comment]
@thousandsofthem yes, that's why it should use pointers.

**Comment by rdallman** [comment]
@thousandsofthem yea, for most fields this will be the same as it was (was already using zero values) -- need to maneuver flags to get them to not have zero values of zero value, i.e. 

```go
flag.Int("max-concurrency", -1, "set max concurrency for this worker")
```

so we can check `if *max-concurrency != -1 { ... }`

**Comment by thousandsofthem** [comment]
sounds good

**Pull request merged**
