### PR TITLE
Crash only if subcommand is executed

### PR DESCRIPTION
**Pull request by Nyarum**
Work for #100

### CODE REVIEW

**Comment by Nyarum** [comment]
@nikhilm please review.

**Comment by nikhilm** [comment]
Could you explain the patch please? Why do we need this repeated code everywhere? Could we just not panic and instead show the help and exit cleanly?

**Comment by Nyarum** [comment]
@nikhilm I would be happy to do that but it still related to iron_go3 repository - https://github.com/iron-io/iron_go3/blob/d1197926301489b15e418c49a0b17a9c42817acd/config/config.go#L121

I can rewrite this code but it not concerned to refactoring.

**Comment by nikhilm** [comment]
Ah. That is unfortunate. `recover()`?

**Comment by Nyarum** [comment]
@nikhilm I think this copy-paste is better than `recover()` because we don't break an execute program. Just do "SetSettings" after an executed subcommand, global options still working for us without env's.

**Pull request merged**
