### PR TITLE
[For Review] Initial cobra, proxy old commands and added functions

### PR DESCRIPTION
**Pull request by pedronasser**
- Moved all old commands to commands package
- Proxying old commands through cobra
- Added functions in new cobra structure

### CODE REVIEW

**Comment by nikhilm** [comment]
I thought the discussion in Slack and the PR here https://github.com/iron-io/ironcli/pull/107 had converged on not rewriting all of cli to add functions functionality. @pedronasser

**Comment by pedronasser** [comment]
@nikhilm, travis asked me to PR this again.
The idea here is not rewrite all of cli, just proxy old commands through cobra and add functions

**Comment by rdallman** [comment]
why? y'all this is ridiculous. we don't need to rewrite the CLI 7 times to
add functions. I don't even have words

**Comment by rdallman** [comment]
I'm going to hunt down the functions CLI which I assume is closed source at time of writing and add a patch to use it myself, which I think we can technically only merge after it's open source since it will be vendored. this is really something else

**Comment by treeder** [comment]
I asked @pedronasser to reopen his branch from the past so we could review it. Everyone can calm down.

**Comment by rdallman** [comment]
closing this since functions cli is moved to functions

**Pull request closed without merging**
