### PR TITLE
[DO NOT MERGE] Stub function command interpreter to help with understanding old flag…

### PR DESCRIPTION
**Pull request by nikhilm**
…s system.

Don't merge until it is ready, but feel free to use this as a template.

@Nyarum

### CODE REVIEW

**Comment by Nyarum** [comment]
@nikhilm what gives understanding this?

**Comment by nikhilm** [comment]
To quote slack:

@rdallman and I believe that the giant refactoring was detrimental to
ironcli code since it was impossible to review and ensure backwards
compatibility. We feel the change was not worth it. Ideally I’d prefer to
move back to the old proven structure, and carry out smaller refactorings.
#107 is created so that the primary objection raised on #79, which was that
the old structure was hard to understand, is provided some assistance. This
way the functions effort is not blocked.

**Comment by Nyarum** [comment]
@nikhilm @rdallman after discussion with @treeder
We can cover all options by tests and for a while push it to beta branch for testing.

Why I want to save the new way:
- We have structures for adding new commands. (It's very easy way was created in the world)
- We have a hide any work with flags, just add it to structure and it's work!
- We have an built-in capability to take any error in one place from any commands.
- If we'll the old way we lose a hardcode standard to write new commands. Because in the old way any developer can do different actions to write a new commands, of course we have a code review but it isn't guarantee.

**Comment by rdallman** [comment]
moving discussion to slack

**Comment by rdallman** [comment]
functions cli is in functions now, closing (thanks for doing this)

**Pull request closed without merging**
