### PR TITLE
WIP Lambda support

### PR DESCRIPTION
**Pull request by nikhilm**
Hey @treeder could you look at this? Adds three commands `create-function`, `test-function` and `publish-function` which are thin wrappers around the `lambda` package in the `lambda` repo.

Edit: Removed lambda from the list of help commands, so this can be merged into master. I have a Trello card to add it back when we are ready to announce the release.

### CODE REVIEW

**Comment by nikhilm** [comment]
Turns out you need to vendor indirect dependencies too (of course!). @treeder @rdallman  I think this is ready to be merged to master. Not complete, but easier to review in chunks.

**Comment by treeder** [comment]
Can we use glide so we don't have to add all these dependencies to git?

**Comment by nikhilm** [comment]
> Can we use glide so we don't have to add all these dependencies to git?

Happy to do another PR for that. I tried, but it isn't easy because either

a) We've to fix ironcli to work with the latest version of iron_go3
b) Specify the exact version of iron_go3 to use in the glide.yaml file. This is proving hard because I can't find certain fields in the canonical iron_go3 history at all, that are used in the currently vendored copy (`Code.DefaultPriority` for example).

**Comment by treeder** [comment]
@nikhilm so you're saying this vendored copy has diverged from the actual iron_go3??

**Comment by nikhilm** [comment]
I am not sure. But the models in vendor don't match what is in the source.
The straightforward git operations couldn't find any history.

**Comment by nikhilm** [comment]
Do you mean replace the canonical with this? The vendor copy is at least 5
months old at this point.

**Comment by treeder** [comment]
Let's ditch all the vendored copies, update iron_go3 with what's missing and use Glide.

**Comment by rdallman** [comment]
:/ we've changed the vendor strategy 3 times already for this repo, is glide even nice? can we try it on something else first?

**Comment by nikhilm** [comment]
We've only tried Glide on Titan. Glide is nice in terms of being fuzzy and
warm and easy to use, but I'm not sure about long term implications. We
would rm the vendor/ dir and have an extra build step where glide goes and
fetches dependencies. Will this be a problem in distributing CLI? It seems
we have release binaries, so it should not be a problem.

**Comment by nikhilm** [comment]
This should be easier to review. Of course, it won't build due to lack of dependencies.

**Comment by nikhilm** [comment]
Ping @treeder

**Pull request merged**
